# Generated by Django 5.0.2 on 2024-02-29 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doktor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ism', models.CharField(max_length=50)),
                ('soha', models.CharField(max_length=50)),
                ('rasmi', models.ImageField(upload_to='doktor')),
            ],
        ),
        migrations.CreateModel(
            name='QabulVaqti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vaqt', models.CharField(max_length=50)),
                ('doktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qabul_vaqt', to='my_app.doktor')),
            ],
        ),
        migrations.CreateModel(
            name='Davolash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foydalanuvchi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qabul_vaqt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.qabulvaqti')),
            ],
        ),
    ]
